POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "this is  atest",
  "important": "test"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "important": "test"
}